# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180119_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
